version: '3.7'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: awesumsawz
      POSTGRES_PASSWORD: dukesilver
      POSTGRES_DB: watcharandomepisode
    volumes:
      - ./postgres:/var/lib/postgresql/data:delegated

  watch-a-random-episode:
    container_name: watch-a-random-episode
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true